cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart/<int:pk>', views.CartDetailView.as_view(), name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

# mediaファイルの設定
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mamazon.urls')),
    path('', include('cart.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # mediaファイルの設定

mamazon/urls.py
from django.urls import path
from . import views

app_name = 'mamazon'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User # Djangoでは推奨していない
from django.conf import settings
from mamazon.models import Product

User = settings.AUTH_USER_MODEL # 推奨されている方法


class Cart(models.Model):
    """
    ショッピングカート
    user: ユーザー名
    products: 商品
    total: 合計金額
    created: カートが作られた日
    updated: カートが追加された日
    """
    user = models.ForeignKey(User,null=True, blank=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)
    total = models.DecimalField(default=0.00, max_digits=9, decimal_places=2) # 小数点を使えるフィールド
    created = models.DateTimeField(auto_now_add=True) # 作成された時間
    updated = models.DateTimeField(auto_now=True) # 更新されたら変更

mamazon/models.py
from django.db import models


class Product(models.Model):
    """
    商品モデル
    name: 商品名
    price: 商品の値段
    description: 商品の説明
    thumbnail: 商品の写真
    """
    name = models.CharField(max_length=150)
    price = models.IntegerField()
    description = models.TextField()
    thumbnail = models.ImageField(upload_to='thumbnails/') # 写真の保存先を指定

    def __str__(self):
        return self.name

cart/views.py
from .models import Cart
from django.views.generic import DetailView


class CartDetailView(DetailView):
    """
    カートの詳細ページ
    """
    model = Cart
    template_name = 'cart/shopping_cart.html'

mamazon/views.py
from django.views.generic import TemplateView, ListView, DetailView
from .models import Product


class Home(TemplateView):
    template_name = 'mamazon/home.html'


class ProductListView(ListView):
    """
    商品のリストを表示
    """
    model = Product
    template_name = 'mamazon/list.html'

    """
    商品の検索機能
    """
    def get_queryset(self):
        queryset = Product.objects.all()
        if 'query' in self.request.GET:
            qs = self.request.GET['query']
            queryset = queryset.filter(name__contains=qs)
        return queryset


class ProductDetailView(DetailView):
    """
    商品の詳細ページ
    """
    model = Product
    template_name = 'mamazon/detail.html'

cart/templates/cart/shopping_cart.html
{% extends 'base.html' %}
{% load static %}


{% block body %}

<div class="span9">
    <ul class="breadcrumb">
        <li><a href="index.html">Home</a> <span class="divider">/</span></li>
        <li class="active"> SHOPPING CART</li>
    </ul>

    <h3> SHOPPING CART [ <small>{{ cart.products.count }} Item(s) </small>]<a href="products.html"
            class="btn btn-large pull-right"><i class="icon-arrow-left"></i> Continue Shopping </a>
    </h3>
    <hr class="soft" />
    <table class="table table-bordered">
        <tr>
            <th> I AM ALREADY REGISTERED </th>
        </tr>
        <tr>
            <td>
                <form class="form-horizontal">
                    <div class="control-group">
                        <label class="control-label" for="inputUsername">Username</label>
                        <div class="controls">
                            <input type="text" id="inputUsername" placeholder="Username">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="inputPassword1">Password</label>
                        <div class="controls">
                            <input type="password" id="inputPassword1" placeholder="Password">
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="controls">
                            <button type="submit" class="btn">Sign in</button> OR <a
                                href="register.html" class="btn">Register Now!</a>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="controls">
                            <a href="forgetpass.html" style="text-decoration:underline">Forgot
                                password?</a>
                        </div>
                    </div>
                </form>
            </td>
        </tr>
    </table>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Product</th>
                <th>Description</th>
                <th>Quantity/Update</th>
                <th>Price</th>
                <th>Discount</th>
                <th>Tax</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>

            <!-- start for loop -->>
            {% for product in cart.products.all %}
            <tr>
                <td> <img width="60" src="{{ product.thumbnail.url }}" alt="" alt="" /></td>
                <!-- thumbnail -->
                <td>{{ product.name }}<br />{{ product.description }}</td> <!-- name, description -->
                <td>
                    <div class="input-append"><input class="span1" style="max-width:34px"
                            placeholder="1" id="appendedInputButtons" size="16" type="text"><button
                            class="btn" type="button"><i class="icon-minus"></i></button><button
                            class="btn" type="button"><i class="icon-plus"></i></button><button
                            class="btn btn-danger" type="button"><i
                                class="icon-remove icon-white"></i></button> </div>
                </td>
                <td>$ {{ product.price }}.00</td> <!-- price -->
                <td>$ ----</td>
                <td>$ ----</td>
                <td>$ {{ product.price }}.00</td> <!-- price -->
            </tr>
            {% endfor %}
            <!-- end for loop -->>

            <tr>
                <td colspan="6" style="text-align:right">Total Price: </td>
                <td> $ {{ cart.total }}</td> <!-- total -->
            </tr>
            <tr>
                <td colspan="6" style="text-align:right">Total Discount: </td>
                <td> $ ----</td>
            </tr>
            <tr>
                <td colspan="6" style="text-align:right">Total Tax: </td>
                <td> $ ----</td>
            </tr>
            <tr>
                <td colspan="6" style="text-align:right"><strong>TOTAL</strong>
                </td>
                <td class="label label-important" style="display:block"> <strong> $
                        {{ cart.total }}
                    </strong>
                </td>
            </tr>
        </tbody>
    </table>


    <table class="table table-bordered">
        <tbody>
            <tr>
                <td>
                    <form class="form-horizontal">
                        <div class="control-group">
                            <label class="control-label"><strong> VOUCHERS CODE: </strong> </label>
                            <div class="controls">
                                <input type="text" class="input-medium" placeholder="CODE">
                                <button type="submit" class="btn"> ADD </button>
                            </div>
                        </div>
                    </form>
                </td>
            </tr>

        </tbody>
    </table>


    <a href="products.html" class="btn btn-large"><i class="icon-arrow-left"></i> Continue Shopping
    </a>
    <a href="login.html" class="btn btn-large pull-right">Next <i class="icon-arrow-right"></i></a>

</div>

{% endblock body %}

mamazon/templates/mamazon/list.html
<!-- homeからテンプレートを継承 -->
{% extends 'mamazon/home.html' %}
{% load static %}


{% block products %}


{% for object in object_list %}
        <li class="span3">
            <div class="thumbnail">
                <a href="{% url 'mamazon:product-detail' object.pk %}"><img
                        src="{{ object.thumbnail.url }}" alt="" /></a>
                <div class="caption">
                    <h5>じゃ{{ object.name }}</h5>
                    <p>
                        じゃ{{ object.description }}
                    </p>

                    <h4 style="text-align:center"><a class="btn" href="{% url 'mamazon:product-detail' object.pk %}"> <i
                                class="icon-zoom-in"></i></a> <a class="btn" href="#">Add to <i
                                class="icon-shopping-cart"></i></a>
                        <a class="btn btn-primary" href="#">$ {{ object.price }}</a></h4>
                </div>
            </div>
        </li>
{% endfor %}

{% endblock products %}